void main() {
    int a;
    int b;
    bool d;
    char c;
    a = 1;
    *b = 1;
    c = 1;
    d = 1;
    c = d;
    a = b + c;
    b = a - d;
    c = c * d;
    d = d / d;
    a = a % d;
    d = !a;
    d = d && b;
    d = d || c;
	b = -a;
	Main = 1;
    a = 123main + 1;
    d = a > d;
    d = a >= d;
    d = b < d;
    d = d <= d;
    d = a != d;
    d = b == d;
	c += b;
    c -= b;
    while (a);
    for (;b;);
}